spring:
  application:
    name: eurekaserver

  security:
    user:
      name: ms-eureka-user
      password: user-eureka-password

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false