spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}